-- Arch Time Pro - privacy and security hardening
-- Run once in Supabase SQL Editor after a database backup.
-- This migration removes direct access to profiles and exposes only controlled RPCs.

begin;

create table if not exists public.legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  accepted_at timestamptz not null default now(),
  source text not null default 'signup',
  unique (user_id, terms_version, privacy_version)
);

alter table public.legal_acceptances enable row level security;
revoke all on public.legal_acceptances from anon, authenticated;

create or replace function public.capture_legal_acceptance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  accepted_at_value timestamptz;
  terms_value text;
  privacy_value text;
begin
  terms_value := nullif(new.raw_user_meta_data ->> 'terms_version', '');
  privacy_value := nullif(new.raw_user_meta_data ->> 'privacy_version', '');

  if terms_value is null or privacy_value is null then
    return new;
  end if;

  begin
    accepted_at_value := coalesce(
      nullif(new.raw_user_meta_data ->> 'legal_accepted_at', '')::timestamptz,
      now()
    );
  exception when others then
    accepted_at_value := now();
  end;

  insert into public.legal_acceptances (
    user_id,
    terms_version,
    privacy_version,
    accepted_at,
    source
  ) values (
    new.id,
    terms_value,
    privacy_value,
    accepted_at_value,
    'signup'
  )
  on conflict (user_id, terms_version, privacy_version) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_legal_acceptance on auth.users;
create trigger on_auth_user_legal_acceptance
after insert on auth.users
for each row execute function public.capture_legal_acceptance();

create or replace function public.has_accepted_legal_documents(
  requested_terms_version text,
  requested_privacy_version text
)
returns boolean
language sql
security definer
set search_path = public
as $$
  select auth.uid() is not null and exists (
    select 1
    from public.legal_acceptances acceptance
    where acceptance.user_id = auth.uid()
      and acceptance.terms_version = requested_terms_version
      and acceptance.privacy_version = requested_privacy_version
  );
$$;

create or replace function public.accept_legal_documents(
  accepted_terms_version text,
  accepted_privacy_version text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Utente non autenticato';
  end if;
  if nullif(trim(accepted_terms_version), '') is null
    or nullif(trim(accepted_privacy_version), '') is null then
    raise exception 'Versione dei documenti non valida';
  end if;

  insert into public.legal_acceptances (
    user_id, terms_version, privacy_version, accepted_at, source
  ) values (
    auth.uid(),
    trim(accepted_terms_version),
    trim(accepted_privacy_version),
    now(),
    'in_app_update'
  )
  on conflict (user_id, terms_version, privacy_version) do nothing;
end;
$$;

create table if not exists public.profile_hourly_cost_history (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  studio_id uuid not null references public.studios(id) on delete cascade,
  hourly_cost numeric not null check (hourly_cost >= 0),
  effective_from timestamptz not null default now(),
  effective_to timestamptz,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (effective_to is null or effective_to > effective_from)
);

create index if not exists profile_hourly_cost_history_lookup_idx
on public.profile_hourly_cost_history(profile_id, effective_from desc);

alter table public.profile_hourly_cost_history enable row level security;
revoke all on public.profile_hourly_cost_history from anon, authenticated;

drop policy if exists "profile_cost_history_admin_select" on public.profile_hourly_cost_history;
create policy "profile_cost_history_admin_select"
on public.profile_hourly_cost_history
for select
to authenticated
using (public.is_admin() and studio_id = public.get_my_studio_id());

grant select on public.profile_hourly_cost_history to authenticated;

insert into public.profile_hourly_cost_history (
  profile_id,
  studio_id,
  hourly_cost,
  effective_from,
  changed_by
)
select
  p.id,
  p.studio_id,
  coalesce(p.hourly_cost, 0),
  now(),
  p.id
from public.profiles p
where p.studio_id is not null
  and not exists (
    select 1
    from public.profile_hourly_cost_history h
    where h.profile_id = p.id
  );

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  studio_id uuid references public.studios(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  entity_type text not null,
  entity_id text,
  action text not null check (action in ('insert', 'update', 'delete')),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_log_studio_created_idx
on public.audit_log(studio_id, created_at desc);

alter table public.audit_log enable row level security;
revoke all on public.audit_log from anon, authenticated;
grant select on public.audit_log to authenticated;

drop policy if exists "audit_log_admin_select" on public.audit_log;
create policy "audit_log_admin_select"
on public.audit_log
for select
to authenticated
using (public.is_admin() and studio_id = public.get_my_studio_id());

create or replace function public.get_my_profile_for_app()
returns table (
  id uuid,
  studio_id uuid,
  full_name text,
  email text,
  role text,
  is_owner boolean,
  hourly_cost numeric,
  active_timer_start text,
  active_timer_project text,
  active_timer_task text,
  active_timer_notes text,
  active_timer_reminder_sent_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    p.id,
    p.studio_id,
    p.full_name,
    p.email,
    p.role::text,
    coalesce(p.is_owner, false),
    case when coalesce(p.is_owner, false) or p.role = 'admin' then p.hourly_cost else null end,
    to_jsonb(p) ->> 'active_timer_start',
    to_jsonb(p) ->> 'active_timer_project',
    to_jsonb(p) ->> 'active_timer_task',
    to_jsonb(p) ->> 'active_timer_notes',
    nullif(to_jsonb(p) ->> 'active_timer_reminder_sent_at', '')::timestamptz
  from public.profiles p
  where p.id = auth.uid();
$$;

create or replace function public.get_team_profiles_for_app()
returns table (
  id uuid,
  studio_id uuid,
  full_name text,
  email text,
  role text,
  is_owner boolean,
  hourly_cost numeric
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Permesso negato';
  end if;

  return query
  select
    p.id,
    p.studio_id,
    p.full_name,
    p.email,
    p.role::text,
    coalesce(p.is_owner, false),
    p.hourly_cost::numeric
  from public.profiles p
  where p.studio_id = public.get_my_studio_id()
  order by p.full_name;
end;
$$;

create or replace function public.get_entries_for_export()
returns table (
  id uuid,
  studio_id uuid,
  project_id uuid,
  project_name text,
  task text,
  duration numeric,
  user_email text,
  user_name text,
  rate numeric,
  notes text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_studio uuid;
  caller_email text;
  caller_is_admin boolean;
begin
  if auth.uid() is null then
    raise exception 'Utente non autenticato';
  end if;

  caller_studio := public.get_my_studio_id();
  caller_is_admin := public.is_admin();
  select p.email into caller_email from public.profiles p where p.id = auth.uid();

  if caller_studio is null or caller_email is null then
    raise exception 'Profilo non valido';
  end if;

  return query
  select
    entry.id,
    entry.studio_id,
    entry.project_id,
    entry.project_name,
    entry.task,
    entry.duration::numeric,
    entry.user_email,
    entry.user_name,
    case when caller_is_admin then entry.rate::numeric else null::numeric end,
    entry.notes,
    entry.created_at
  from public.entries entry
  where entry.studio_id = caller_studio
    and (caller_is_admin or entry.user_email = caller_email)
  order by entry.created_at desc;
end;
$$;

create or replace function public.set_my_timer_state(
  timer_start text default null,
  timer_project text default null,
  timer_task text default null,
  timer_notes text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Utente non autenticato';
  end if;

  update public.profiles
  set
    active_timer_start = timer_start,
    active_timer_project = timer_project,
    active_timer_task = timer_task,
    active_timer_notes = timer_notes,
    active_timer_reminder_sent_at = null
  where id = auth.uid();

  if not found then
    raise exception 'Profilo non trovato';
  end if;
end;
$$;

create or replace function public.join_studio_with_code(invite_studio_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.profiles%rowtype;
begin
  if auth.uid() is null or invite_studio_id is null then
    raise exception 'Invito non valido';
  end if;

  select * into current_profile
  from public.profiles
  where id = auth.uid()
  for update;

  if current_profile.id is null or current_profile.studio_id is not null then
    raise exception 'Profilo non disponibile per questo invito';
  end if;

  if not exists (select 1 from public.studios where id = invite_studio_id) then
    raise exception 'Studio non trovato';
  end if;

  update public.profiles
  set studio_id = invite_studio_id, role = 'staff', is_owner = false
  where id = auth.uid();
end;
$$;

create or replace function public.set_my_hourly_cost(new_hourly_cost numeric)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.profiles%rowtype;
begin
  select * into current_profile
  from public.profiles
  where id = auth.uid()
  for update;

  if current_profile.id is null
     or not (coalesce(current_profile.is_owner, false) or current_profile.role = 'admin') then
    raise exception 'Permesso negato';
  end if;

  if new_hourly_cost is null or new_hourly_cost < 0 then
    raise exception 'Costo orario non valido';
  end if;

  if current_profile.hourly_cost is distinct from new_hourly_cost then
    update public.profile_hourly_cost_history
    set effective_to = now()
    where profile_id = current_profile.id and effective_to is null;

    insert into public.profile_hourly_cost_history (
      profile_id, studio_id, hourly_cost, effective_from, changed_by
    ) values (
      current_profile.id, current_profile.studio_id, new_hourly_cost, now(), auth.uid()
    );

    update public.profiles
    set hourly_cost = new_hourly_cost
    where id = current_profile.id;

    insert into public.audit_log (
      studio_id, actor_id, entity_type, entity_id, action, old_data, new_data
    ) values (
      current_profile.studio_id,
      auth.uid(),
      'profile',
      current_profile.id::text,
      'update',
      jsonb_build_object('hourly_cost', current_profile.hourly_cost),
      jsonb_build_object('hourly_cost', new_hourly_cost)
    );
  end if;
end;
$$;

create or replace function public.update_team_member_for_app(
  target_profile_id uuid,
  target_full_name text,
  target_hourly_cost numeric,
  target_role text,
  transfer_ownership boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_profile public.profiles%rowtype;
  old_profile public.profiles%rowtype;
  final_role text;
  final_owner boolean;
begin
  select * into caller_profile
  from public.profiles
  where id = auth.uid()
  for update;

  if caller_profile.id is null
     or not (coalesce(caller_profile.is_owner, false) or caller_profile.role = 'admin') then
    raise exception 'Permesso negato';
  end if;

  select * into old_profile
  from public.profiles
  where id = target_profile_id
    and studio_id = caller_profile.studio_id
  for update;

  if old_profile.id is null then
    raise exception 'Collaboratore non trovato';
  end if;

  if nullif(trim(target_full_name), '') is null then
    raise exception 'Nome obbligatorio';
  end if;

  if target_hourly_cost is null or target_hourly_cost < 0 then
    raise exception 'Costo orario non valido';
  end if;

  if target_role not in ('admin', 'staff', 'inactive') then
    raise exception 'Ruolo non valido';
  end if;

  if coalesce(old_profile.is_owner, false) and old_profile.id <> caller_profile.id then
    raise exception 'Solo il proprietario può modificare il proprio profilo';
  end if;

  if not coalesce(caller_profile.is_owner, false)
     and (coalesce(old_profile.is_owner, false) or old_profile.role = 'admin')
     and old_profile.id <> caller_profile.id then
    raise exception 'Un admin non può modificare owner o altri admin';
  end if;

  if old_profile.id = caller_profile.id
     and target_role is distinct from old_profile.role
     and not transfer_ownership then
    raise exception 'Non puoi modificare il tuo ruolo';
  end if;

  final_role := target_role;
  final_owner := coalesce(old_profile.is_owner, false);

  if transfer_ownership then
    if not coalesce(caller_profile.is_owner, false)
       or old_profile.id = caller_profile.id then
      raise exception 'Trasferimento di proprietà non consentito';
    end if;

    update public.profiles
    set is_owner = false, role = 'admin'
    where id = caller_profile.id;

    insert into public.audit_log (
      studio_id, actor_id, entity_type, entity_id, action, old_data, new_data
    ) values (
      caller_profile.studio_id,
      auth.uid(),
      'profile',
      caller_profile.id::text,
      'update',
      jsonb_build_object('role', caller_profile.role, 'is_owner', caller_profile.is_owner),
      jsonb_build_object('role', 'admin', 'is_owner', false)
    );

    final_role := 'admin';
    final_owner := true;
  elsif coalesce(old_profile.is_owner, false) then
    final_role := 'admin';
    final_owner := true;
  else
    final_owner := false;
  end if;

  if old_profile.hourly_cost is distinct from target_hourly_cost then
    update public.profile_hourly_cost_history
    set effective_to = now()
    where profile_id = old_profile.id and effective_to is null;

    insert into public.profile_hourly_cost_history (
      profile_id, studio_id, hourly_cost, effective_from, changed_by
    ) values (
      old_profile.id,
      old_profile.studio_id,
      target_hourly_cost,
      now(),
      auth.uid()
    );
  end if;

  update public.profiles
  set
    full_name = trim(target_full_name),
    hourly_cost = target_hourly_cost,
    role = final_role,
    is_owner = final_owner
  where id = old_profile.id;

  insert into public.audit_log (
    studio_id, actor_id, entity_type, entity_id, action, old_data, new_data
  ) values (
    old_profile.studio_id,
    auth.uid(),
    'profile',
    old_profile.id::text,
    'update',
    jsonb_build_object(
      'full_name', old_profile.full_name,
      'hourly_cost', old_profile.hourly_cost,
      'role', old_profile.role,
      'is_owner', old_profile.is_owner
    ),
    jsonb_build_object(
      'full_name', trim(target_full_name),
      'hourly_cost', target_hourly_cost,
      'role', final_role,
      'is_owner', final_owner
    )
  );
end;
$$;

create or replace function public.get_hourly_cost_at(
  target_profile_id uuid,
  effective_at timestamptz
)
returns numeric
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (
      select h.hourly_cost
      from public.profile_hourly_cost_history h
      where h.profile_id = target_profile_id
        and h.effective_from <= coalesce(effective_at, now())
        and (h.effective_to is null or h.effective_to > coalesce(effective_at, now()))
      order by h.effective_from desc
      limit 1
    ),
    (select p.hourly_cost from public.profiles p where p.id = target_profile_id),
    0
  );
$$;

revoke all on function public.get_hourly_cost_at(uuid, timestamptz) from public, anon, authenticated;

create or replace function public.create_entry_for_app(
  entry_project_id uuid,
  entry_task text,
  entry_duration numeric,
  entry_notes text default '',
  entry_created_at timestamptz default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_profile public.profiles%rowtype;
  target_project public.projects%rowtype;
  new_entry_id uuid;
  effective_at timestamptz;
  effective_cost numeric;
begin
  if auth.uid() is null then raise exception 'Utente non autenticato'; end if;
  if entry_project_id is null then raise exception 'Progetto obbligatorio'; end if;
  if entry_duration is null or entry_duration <= 0 then raise exception 'Durata non valida'; end if;

  select * into caller_profile from public.profiles where id = auth.uid();
  if caller_profile.id is null or caller_profile.studio_id is null then
    raise exception 'Profilo non valido';
  end if;

  select * into target_project
  from public.projects
  where id = entry_project_id
    and studio_id = caller_profile.studio_id
    and coalesce(is_archived, false) = false;

  if target_project.id is null then raise exception 'Progetto non trovato o archiviato'; end if;

  effective_at := coalesce(entry_created_at, now());
  effective_cost := public.get_hourly_cost_at(caller_profile.id, effective_at);

  insert into public.entries (
    studio_id, project_id, project_name, task, duration,
    user_email, user_name, rate, notes, created_at
  ) values (
    caller_profile.studio_id,
    target_project.id,
    target_project.name,
    coalesce(nullif(trim(entry_task), ''), 'Generico'),
    entry_duration,
    caller_profile.email,
    caller_profile.full_name,
    effective_cost * entry_duration,
    coalesce(entry_notes, ''),
    effective_at
  ) returning id into new_entry_id;

  return new_entry_id;
end;
$$;

create or replace function public.update_entry_for_app(
  entry_id uuid,
  entry_project_id uuid,
  entry_task text,
  entry_duration numeric,
  entry_notes text default '',
  entry_created_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_profile public.profiles%rowtype;
  target_entry public.entries%rowtype;
  target_project public.projects%rowtype;
  effective_at timestamptz;
  effective_cost numeric;
begin
  if auth.uid() is null then raise exception 'Utente non autenticato'; end if;
  if entry_id is null then raise exception 'Attività obbligatoria'; end if;
  if entry_project_id is null then raise exception 'Progetto obbligatorio'; end if;
  if entry_duration is null or entry_duration <= 0 then raise exception 'Durata non valida'; end if;

  select * into caller_profile from public.profiles where id = auth.uid();
  if caller_profile.id is null or caller_profile.studio_id is null then
    raise exception 'Profilo non valido';
  end if;

  select * into target_entry
  from public.entries
  where id = entry_id and studio_id = caller_profile.studio_id;

  if target_entry.id is null then raise exception 'Attività non trovata'; end if;
  if target_entry.user_email is distinct from caller_profile.email then
    raise exception 'Puoi modificare solo le attività inserite da te';
  end if;

  select * into target_project
  from public.projects
  where id = entry_project_id
    and studio_id = caller_profile.studio_id
    and coalesce(is_archived, false) = false;

  if target_project.id is null then raise exception 'Progetto non trovato o archiviato'; end if;

  effective_at := coalesce(entry_created_at, target_entry.created_at);
  effective_cost := coalesce(
    target_entry.rate / nullif(target_entry.duration, 0),
    public.get_hourly_cost_at(caller_profile.id, effective_at)
  );

  update public.entries
  set
    project_id = target_project.id,
    project_name = target_project.name,
    task = coalesce(nullif(trim(entry_task), ''), 'Generico'),
    duration = entry_duration,
    notes = coalesce(entry_notes, ''),
    created_at = effective_at,
    user_email = caller_profile.email,
    user_name = caller_profile.full_name,
    rate = effective_cost * entry_duration
  where id = target_entry.id;
end;
$$;

create or replace function public.audit_operational_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_before jsonb;
  row_after jsonb;
  audit_studio_id uuid;
  audit_entity_id text;
begin
  delete from public.audit_log
  where created_at < now() - interval '24 months';

  row_before := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  row_after := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  audit_studio_id := coalesce(
    nullif(row_after ->> 'studio_id', '')::uuid,
    nullif(row_before ->> 'studio_id', '')::uuid
  );
  audit_entity_id := coalesce(row_after ->> 'id', row_before ->> 'id');

  insert into public.audit_log (
    studio_id, actor_id, entity_type, entity_id, action, old_data, new_data
  ) values (
    audit_studio_id,
    auth.uid(),
    tg_table_name,
    audit_entity_id,
    lower(tg_op),
    row_before,
    row_after
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function public.capture_legal_acceptance() from public, anon, authenticated;
revoke all on function public.audit_operational_change() from public, anon, authenticated;

drop trigger if exists audit_projects_changes on public.projects;
create trigger audit_projects_changes
after update or delete on public.projects
for each row execute function public.audit_operational_change();

drop trigger if exists audit_entries_changes on public.entries;
create trigger audit_entries_changes
after update or delete on public.entries
for each row execute function public.audit_operational_change();

drop trigger if exists audit_expenses_changes on public.expenses;
create trigger audit_expenses_changes
after update or delete on public.expenses
for each row execute function public.audit_operational_change();

revoke all on function public.get_my_profile_for_app() from public, anon;
revoke all on function public.has_accepted_legal_documents(text, text) from public, anon;
revoke all on function public.accept_legal_documents(text, text) from public, anon;
revoke all on function public.get_team_profiles_for_app() from public, anon;
revoke all on function public.get_entries_for_export() from public, anon;
revoke all on function public.set_my_timer_state(text, text, text, text) from public, anon;
revoke all on function public.join_studio_with_code(uuid) from public, anon;
revoke all on function public.set_my_hourly_cost(numeric) from public, anon;
revoke all on function public.update_team_member_for_app(uuid, text, numeric, text, boolean) from public, anon;
revoke all on function public.create_entry_for_app(uuid, text, numeric, text, timestamptz) from public, anon;
revoke all on function public.update_entry_for_app(uuid, uuid, text, numeric, text, timestamptz) from public, anon;

grant execute on function public.get_my_profile_for_app() to authenticated;
grant execute on function public.has_accepted_legal_documents(text, text) to authenticated;
grant execute on function public.accept_legal_documents(text, text) to authenticated;
grant execute on function public.get_team_profiles_for_app() to authenticated;
grant execute on function public.get_entries_for_export() to authenticated;
grant execute on function public.set_my_timer_state(text, text, text, text) to authenticated;
grant execute on function public.join_studio_with_code(uuid) to authenticated;
grant execute on function public.set_my_hourly_cost(numeric) to authenticated;
grant execute on function public.update_team_member_for_app(uuid, text, numeric, text, boolean) to authenticated;
grant execute on function public.create_entry_for_app(uuid, text, numeric, text, timestamptz) to authenticated;
grant execute on function public.update_entry_for_app(uuid, uuid, text, numeric, text, timestamptz) to authenticated;

-- Profiles contain economic and privilege columns. They are no longer exposed directly.
revoke select, insert, update, delete on public.profiles from authenticated;

commit;
