begin;

alter table public.projects
add column if not exists is_demo boolean not null default false;

update public.projects as project
set is_demo = true
from public.studios as studio
where project.studio_id = studio.id
  and studio.demo_generated = true
  and project.is_demo = false
  and (
    (project.name = 'Villa sul Lago' and project.client = 'Famiglia Rossi')
    or (project.name = 'Cantiere Via Roma' and project.client = 'Condominio Roma')
  );

alter table public.profiles
add column if not exists lifecycle_emails_enabled boolean not null default true;

alter table public.profiles
add column if not exists lifecycle_email_token uuid not null default gen_random_uuid();

create unique index if not exists profiles_lifecycle_email_token_uidx
on public.profiles(lifecycle_email_token);

create table if not exists public.lifecycle_email_log (
  id bigint generated by default as identity primary key,
  studio_id uuid not null references public.studios(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  event_key text not null,
  recipient_email text not null,
  recipient_name text,
  studio_name text,
  days_left integer,
  status text not null default 'claimed',
  claimed_at timestamptz not null default now(),
  sent_at timestamptz,
  last_error text,
  constraint lifecycle_email_log_event_check check (
    event_key in (
      'no_project_24h',
      'project_no_hours_48h',
      'inactive_7d',
      'trial_7d',
      'trial_3d',
      'trial_1d',
      'trial_expired'
    )
  ),
  constraint lifecycle_email_log_status_check check (
    status in ('claimed', 'sent')
  ),
  constraint lifecycle_email_log_studio_event_unique unique (studio_id, event_key)
);

alter table public.lifecycle_email_log enable row level security;

create or replace function public.claim_trial_lifecycle_emails(max_rows integer default 50)
returns table (
  log_id bigint,
  studio_id uuid,
  profile_id uuid,
  event_key text,
  recipient_email text,
  recipient_name text,
  studio_name text,
  days_left integer,
  unsubscribe_token uuid
)
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.lifecycle_email_log as stale
  where stale.status = 'claimed'
    and stale.claimed_at < now() - interval '2 hours';

  return query
  with studio_activity as (
    select
      s.id as studio_id,
      s.name as studio_name,
      s.created_at,
      owner_profile.id as profile_id,
      owner_profile.email as recipient_email,
      owner_profile.full_name as recipient_name,
      owner_profile.lifecycle_email_token as unsubscribe_token,
      coalesce(project_stats.project_count, 0) as project_count,
      coalesce(entry_stats.entry_count, 0) as entry_count,
      entry_stats.last_entry_at,
      greatest(
        0,
        ceil(extract(epoch from ((s.created_at + interval '30 days') - now())) / 86400.0)::integer
      ) as days_left
    from public.studios s
    join lateral (
      select p.id, p.email, p.full_name, p.lifecycle_email_token
      from public.profiles p
      where p.studio_id = s.id
        and p.lifecycle_emails_enabled = true
        and p.email is not null
        and trim(p.email) <> ''
        and (p.is_owner = true or p.role in ('admin', 'owner'))
      order by p.is_owner desc nulls last, p.id
      limit 1
    ) owner_profile on true
    left join lateral (
      select count(*)::integer as project_count
      from public.projects pr
      where pr.studio_id = s.id
        and pr.is_demo = false
    ) project_stats on true
    left join lateral (
      select count(*)::integer as entry_count, max(e.created_at) as last_entry_at
      from public.entries e
      join public.projects pr on pr.id = e.project_id
      where e.studio_id = s.id
        and pr.is_demo = false
    ) entry_stats on true
    where s.subscription_status = 'trialing'
      and s.stripe_subscription_id is null
  ),
  candidates as (
    select
      activity.*,
      rule.event_key,
      rule.priority
    from studio_activity activity
    cross join lateral (
      values
        (
          'trial_expired'::text,
          activity.created_at <= now() - interval '30 days',
          1
        ),
        (
          'trial_1d'::text,
          activity.created_at <= now() - interval '29 days'
            and activity.created_at > now() - interval '30 days',
          2
        ),
        (
          'trial_3d'::text,
          activity.created_at <= now() - interval '27 days'
            and activity.created_at > now() - interval '29 days',
          3
        ),
        (
          'trial_7d'::text,
          activity.created_at <= now() - interval '23 days'
            and activity.created_at > now() - interval '27 days',
          4
        ),
        (
          'inactive_7d'::text,
          activity.created_at <= now() - interval '7 days'
            and activity.created_at > now() - interval '23 days'
            and activity.entry_count > 0
            and activity.last_entry_at <= now() - interval '7 days',
          5
        ),
        (
          'project_no_hours_48h'::text,
          activity.created_at <= now() - interval '48 hours'
            and activity.created_at > now() - interval '10 days'
            and activity.project_count > 0
            and activity.entry_count = 0,
          6
        ),
        (
          'no_project_24h'::text,
          activity.created_at <= now() - interval '24 hours'
            and activity.created_at > now() - interval '7 days'
            and activity.project_count = 0,
          7
        )
    ) rule(event_key, eligible, priority)
    where rule.eligible
  ),
  selected_candidates as (
    select *
    from candidates
    order by priority, created_at
    limit greatest(1, least(coalesce(max_rows, 50), 200))
  ),
  inserted as (
    insert into public.lifecycle_email_log (
      studio_id,
      profile_id,
      event_key,
      recipient_email,
      recipient_name,
      studio_name,
      days_left
    )
    select
      candidate.studio_id,
      candidate.profile_id,
      candidate.event_key,
      lower(trim(candidate.recipient_email)),
      candidate.recipient_name,
      candidate.studio_name,
      candidate.days_left
    from selected_candidates candidate
    on conflict on constraint lifecycle_email_log_studio_event_unique do nothing
    returning
      id,
      lifecycle_email_log.studio_id,
      lifecycle_email_log.profile_id,
      lifecycle_email_log.event_key,
      lifecycle_email_log.recipient_email,
      lifecycle_email_log.recipient_name,
      lifecycle_email_log.studio_name,
      lifecycle_email_log.days_left
  )
  select
    inserted.id,
    inserted.studio_id,
    inserted.profile_id,
    inserted.event_key,
    inserted.recipient_email,
    inserted.recipient_name,
    inserted.studio_name,
    inserted.days_left,
    profiles.lifecycle_email_token
  from inserted
  join public.profiles on profiles.id = inserted.profile_id;
end;
$$;

revoke all on function public.claim_trial_lifecycle_emails(integer) from public;
revoke all on function public.claim_trial_lifecycle_emails(integer) from anon;
revoke all on function public.claim_trial_lifecycle_emails(integer) from authenticated;
grant execute on function public.claim_trial_lifecycle_emails(integer) to service_role;

commit;
